{% set name = "pylint-venv" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylint-venv-{{ version }}.tar.gz
  sha256: 3594955502fdee83c98bfcc8c14cd615e6c7c3608aea525df84853ce79f296bf

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - python >=3.6

test:
  imports:
    - pylint_venv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jgosmann/pylint-venv/
  summary: pylint-venv provides a Pylint init-hook to use the same Pylint installation with different virtual environments.
  description: |
      Pylint does not respect the currently activated virtualenv if it is not installed in every virtual environment individually. 
      This module provides a Pylint init-hook to use the same Pylint installation with different virtual environments.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://github.com/jgosmann/pylint-venv/
  dev_url: https://github.com/jgosmann/pylint-venv/



extra:
  recipe-maintainers:
    - mwawra
