{% set name = "pylint-venv" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylint-venv-{{ version }}.tar.gz
  sha256: 6c5317a6ac703a682bc77ab5819a3b7431d6df7fac91fd53555b3f7563cbf0bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pylint_venv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jgosmann/pylint-venv/
  summary: pylint-venv provides a Pylint init-hook to use the same Pylint installation with different virtual environments.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mwawra
